//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanthuctap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public string Mahd { get; set; }
        public string Madk { get; set; }
        public Nullable<int> Dntt { get; set; }
        public Nullable<int> Dongia { get; set; }
    
        public virtual DIENKE DIENKE { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
