//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanthuctap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHOADON
    {
        public int Mact { get; set; }
        public string Mahd { get; set; }
        public int Dntt { get; set; }
        public decimal Dongia { get; set; }
        public System.DateTime Ngaythanhlap { get; set; }
        public string Makh { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual KHANHHANG KHANHHANG { get; set; }
    }
}
