//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanthuctap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [MetadataType(typeof(Models.CGiadien))]
    public partial class GIADIEN
    {
        public int Mabac { get; set; }
        public string Tenbac { get; set; }
        public int Tusokw { get; set; }
        public int Densokw { get; set; }
        public decimal Dongia { get; set; }
        public System.DateTime Ngaythanhlap { get; set; }
    }
}
