//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanthuctap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIADIEN
    {
        public int Mabac { get; set; }
        public string Tenbac { get; set; }
        public Nullable<int> Tusokw { get; set; }
        public Nullable<int> Densokw { get; set; }
        public Nullable<int> Dongia { get; set; }
        public Nullable<System.DateTime> Ngaythanhlap { get; set; }
    }
}
